### ISSUE TITLE
weird duplicate list bug

### ISSUE THREAD

**Issue by giithubbb** [jewbmx/repo#14]
Hey man just reporting a strange bug i seem to have found
If we select "show trakt liked userlists" in settings,then when we go to my userlists then there is duplicate lists of everything we made ourselves
I think whats happening is it is showing liked lists from other users (as it should be) but also showing our personal lists and then showing our personal lists again as "liked lists" so is showing those as duplicate 
Also movie lists appear in the tv lists section and vice versa (but thats mehhh lol)

Another weird one is that if we have selected "enable fanart.tv artwork" in the settings,then trakt lists appear blank,or if you add anything to trakt list while this option is not selected then select the option afterwards,the new stuff you add to trakt list wont show up.It needs to be unselected to see the list.

Hope that makes sense lol
keep up the good work man peace out

**Comment by jewbmx** [comment]
If you ever read the change log youd see that the liked userlist setting is tossed in to help ditch the dupes for people that dont wanna see em, seeing dupes is because its loading all your lists and liked ones which your made lists are auto liked.
Your seeing your lists in movies and shows because a list can be both but only loads one or the other for the type corresponding to the selected section. 
And as for your fanart issue you probably need to clean your cache and restart the addon because i doubt the addon is gonna do it for you lol.

What i could do tho is segregation for the userlists section to pamper everyones needs, and ditch the setting for liked lists. Also if the fanart issue is still persistent after a cleansing i could just ditch the garbage and leave everyone to the glorious stock artwork collection i use 😉

**Comment by jewbmx** [comment]
I split up the userlist sections now to be separate listings so i dont see a reason to keep this issue open. You can test it out when i push my next update and let me know if any issues persist. (Didnt touch any artwork related code so that will still be the same lol.)
