### ISSUE TITLE
Chat of May

### ISSUE THREAD

**Issue by jewbmx** [jewbmx/repo#24]
Gonna change it up this time.
And since so many people wanna copy our work without learning to do it on their own imma skip the domain share. (Dont got many new ones this month anyways lol.)

As for a little lesson on cleaning your own mess up, start by loading up every scraper enabled with a basic search of a new and old item, then slide down the list selecting each scraper that shows results. When you get to the bottom of the list move all the selected scrapers to a temp folder and run again for any missed, mental note the ones that run passed 30% if your down to 40 or less scrapers because they be laggy poo, broken, or need to be checked. Should be down to only busted junk by the time you do your 4 test searchs unless you made poor choices.

**Comment by jewbmx** [comment]
Damn started adding some new networks, ended up going thru all of em one by one on tvmaze and in the addon lol. Then went to add a couple lists for Lifetime and Hallmark which turned into 20+ between the two lmao.

**Comment by jewbmx** [comment]
If anyone spots a duped host in your results let me know here and i will add it to the limit code, like mymovie4k - vidzi  or  mymovie4k/putlockerplus - videobee.

How do you know what is spam or what is ok? 3 or more results for 1 host from 1 scraper is spam. (Not counting Dbird or Torr.) Granted there is a few scrapers or hosts that will produce bulkish results like series9 or xstreamcdn but those are whitelisted lol. Note that limit coding is only for normal/free results, any and all premo results can fuck off besides the rapidgator disable option lol.

**Comment by jewbmx** [comment]
I noticed a pretty obvious way to limit the hosts today thats a hella lot easier and its just 1 line of code. Im updating all the en scrapers with it and running a few tests but seems to be all good. My previous post about watching for dupes can be ignored lol

**Comment by bjgood** [comment]
What's an example of this new code? I'd like to start changing them over on my setup.

Also, yesterday, I found that adding a simple piece of code to a scraper limits it to one series. I started using vidics again because it gives me working links for Poirot. It's pretty much useless for anything else (at least for me). So, I added "if not 'poirot' in pageURL: continue" within the def sources(self, data, hostDict, hostprDict) function. Now vidics only show results for the Poirot tv series, and nothing else. Since streamango and mycloud don't work for me at all (which makes plocker useless), I needed to find another source for that series. Thus, vidics.

Sorry for asking, but when you have some spare time, could you look vidics over and see if there's a better place to put that bit of code? You're far more knowledgeable about coding than me.

Later...

**Comment by jewbmx** [comment]
The new code im using is as simple as that lol, seen this in a scraper Tempest fixed a little while back...
if url in str(sources): continue
So i tinkered around and now its this easy...
if host in str(sources): continue


You most likely need to email me your scraper to have me look at it, the vidics i have saved is a pos. Has bs4 in it for a 'memory marker' (not code talk, stoner talk.)

**Comment by jewbmx** [comment]
The limit code used before was good for multiple but since i said fuck it and like 1 of each per scraper that new line saves some time and is pretty

**Comment by bjgood** [comment]
Your code snippet works. Wow. So simple. And it frees up a lot of space. Nice.

And I put my revised bit of code (if not 'poirot' in url: return) in the def _sessionRequest function, and it works there. Thanks for giving me directions on how to approach it.

Later...

**Comment by jewbmx** [comment]
Id like to try and add that or something like it to the main sources.py file for url so there is no more duped results lol

**Comment by doko-desuka** [comment]
@jewbmx I was going to suggest the same, adding it to sources.py after all the scraping is done, instead of that "if url in str(sources)" way in each scraper because that uses string comparison, it's slower.
Doing it on sources.py has the benefit that you know all the sources around, there might be dupes even across unrelated scrapers (probably rare though).  

If you're coding your own add-on from scratch you can do this wherever you feel appropriate, but if you're using an Exodus fork there's a convenient place for that, it's the 'sourcesFilter()' function:  
https://github.com/covenantkodi/script.module.covenant/blob/master/lib/resources/lib/modules/sources.py#L797

You can replace that marked line with all of this, but I didn't test it:
```
def uniqueSourcesGen(sources):
  uniqueURLs = set()
  for source in sources:
    if source['url'] not in uniqueURLs:
      uniqueURLs.add(source['url'])
      yield source # Yield the unique source.
    else:
      pass # Ignore further duped sources.

self.sources = list(uniqueSourcesGen(filter))
```

**Comment by jewbmx** [comment]
Ive done a little testing and the url line is pretty much useless/unneeded in about all the scrapers besides torr and dbird. Ive also tried a few ideas like what you thought up doko but no matter how i run it if i do a bulky search it pretty much doubles the search time so i gave up on it lol

**Comment by jewbmx** [comment]
Im probably gonna be a little afk for the next few days or week lol, imma do one more update then start tearing thru the indexers to clean up a little and sort some shit out like all the lists and boxset shit

**Comment by jewbmx** [comment]
Found a new site today thats nice but not sure if its gonna be a easy one since the urls are odd as hell.

view-source:https://watchseriestv.tv/episode/182412-The+Simpsons

Once you hit that page tho its super easy lol

**Comment by bjgood** [comment]
> ***If ya wanna make that host limit into a setting you can have better odds on the weird shows that dont offer shit for results, like what bj seems to watch.

Very funny.

**Comment by jewbmx** [comment]
Lol i was being serious, think you can add a setting check thats like tor_enabled simply by adding 'and blah =blah true'

**Comment by jewbmx** [comment]
Just fooled around with that setting idea and it works easy lol.

`def limit_hosts():
    enabled = control.setting('limit_hosts')
    if enabled == 'true':
        return True
    else:
        return False
`

In source_utils and then...

`if source_utils.limit_hosts() is True and host in str(sources): continue`

Bool setting added to your addon and its done lol

**Comment by jewbmx** [comment]
Shit now im stuck trying to decide if i wanna put it back in or not lol, figures once i delete it i get a doubt. It could come in handy and the randos that use my poo can turn it off if they wanna be about them high numbers lol

**Comment by jewbmx** [comment]
Im about to make myself like 15 omdb api keys and randomize them fuckers for testing lol. The limit on em blows for running tests

**Comment by host505** [comment]
@doko-desuka you're an asset! Your filter-out dups code seems to be working great - brief tested on my fork.
Doesn't seem to be adding much delay either, even on my low-end Android phone.

**Comment by jewbmx** [comment]
Damn i forgot all about trying that out. Just noticed a flaw in the host limiting, it dont account for quality so you get stuck with your favorite host being 1080p instead of seeing a sd source lol

**Comment by jewbmx** [comment]
Forgot to add a note in the changelog about adding trakt manager to the sky channels indexer too lol. It works fine if anyones thinking about it too

**Comment by jewbmx** [comment]
The dupe check code is definitely working and not seeing any issues either. Just ran it on a episode test using 6 bulky scrapers and the results went from 926 to 816. Nicely done and host505 im totally jackin your version because that setting addition is top notch smart lol :)

**Comment by host505** [comment]
Damn, doesn't seem to _always_ work, at least on my fork. That's why I put it on a try/except, so at least it yields the normal results when it won't work.
When it doesn't work, log says this:
```
  File "...\plugin.video.theoath\resources\lib\modules\sources.py", line 792, in sourcesFilter
    self.sources = list(uniqueSourcesGen(filter))
  File "...\plugin.video.theoath\resources\lib\modules\sources.py", line 786, in uniqueSourcesGen
    if source['url'] not in uniqueURLs:
TypeError: unhashable type: 'dict'
```

**Comment by jewbmx** [comment]
I havent ran it enough to get a fail lol, been too high so i only did 2 runs with it in and out on 6 to 8 scrapers. Your touches are about to make testing it way easier

**Comment by host505** [comment]
@jewbmx I just tested the code with your add-on, and it doesn't seem to cause the issues I have on mine (at least on the titles that I have problems on).
Now I have to figure out why it happens on mine. Maybe a scraper is causing this, but I tested with openscrapers and the other scraper package, happens on both.

**Comment by jewbmx** [comment]
Thats probably the changes between Tempest and mine compared to others. Unless you did some other recent changes that could be making it odd.

**Comment by doko-desuka** [comment]
> Damn, doesn't seem to always work, at least on my fork. That's why I put it on a try/except, so at least it yields the normal results when it won't work.

Ooh, nice catch. You shouldn't need the try/catch if you replace that function with this:

```
def uniqueSourcesGen(sources):
  uniqueURLs = set()
  for source in sources:
    url = source['url']
    if isinstance(url, basestring):
      if url not in uniqueURLs:
        uniqueURLs.add(url)
        yield source # Yield the unique source.
      else:
        pass # Ignore duped sources.
    else:
      yield source # Always yield non-string url sources.
```

It's from a few scrapers that store a dict() object in the 'url' key of their sources, with data to be used in the 'resolve()' function of that scraper, like web session cookies, user-agent etc.

**Comment by host505** [comment]
Figured it should be a scraper causing this, since it occurred on _some_ searches, not always.
Thanks for saving me the trouble of testing them all one by one :)
I think I'm gonna keep the try/except until further testing. You think it's causing some bad effect?
Again, great feature you've added there, thanks.

**Comment by doko-desuka** [comment]
By the way, in Exodus forks, all of these lines...
https://github.com/covenantkodi/script.module.covenant/blob/master/lib/resources/lib/modules/sources.py#L794-L797

...can be replaced with a single line:
`self.sources = list(uniqueSourcesGen(self.sources))`

Because all those lines do is store in that `filter` list all the sources that have their `direct` values set to `False`, or set to `True`; since any source is always either one of these, in the end it's just an expensive way to copy the sources list.  
This change alone should give a small speedup without any changes to behavior.

@host505 don't mention it, that was a very simple thing. Thanks for testing.

**Comment by doko-desuka** [comment]
The try/catch shouldn't cause any noticeable impact, it's super fast and the preferred way to do things in Python, it's actually bad form not to use it (guilty xD).  
I personally don't like it because it eats up all errors and I need to go in and comment it out to see what error is actually happening.

**Comment by host505** [comment]
I watched that error on the exception (https://github.com/host505/plugin.video.theoath/blob/master/resources/lib/modules/sources.py#L797), of course I had to input logging manually there.

**Comment by jewbmx** [comment]
Man i got like 600+ userlists in scrubs and still cant figure out something to watch lol. Im even all caught up on my shows

**Comment by jewbmx** [comment]
Damn the codes fresh as hell and yet theres already 3 forks updated with it lol. Guess the idea was a popular one.

**Comment by jewbmx** [comment]
Putting all my shit on hold for a bit because i just noticed i never fixed the imdb watchlist lol. It seems to be broken in everyones addons so i think we all gotta use a pc to scrape the pages and update the code for em.

**Comment by host505** [comment]
@jewbmx imdb watchlist works here with your add-on.

**Comment by jewbmx** [comment]
For real? Maybe i just been puttin my shit in wrong all this time

**Comment by host505** [comment]
Are you putting you imdb username in settings?
You have to put your user id, not username.
It's the urxxxxxxxx part of the URL on your imdb profile page.

**Comment by jewbmx** [comment]
Yea it always fails lol even tho its loaded with 30 items

**Comment by jewbmx** [comment]
Nevermind i just opened it up in my phones app and tried to toggle the private setting and that got it to work now. That is one stupid ass little issue

**Comment by host505** [comment]
Yeah it has to be public - same for other imdb custom lists too.

**Comment by jewbmx** [comment]
Thats dumb for your own watchlist lol. Glad you tried it and said something, now i dont gotta touch my laptop and can keep burning thru avatar episodes

**Comment by jewbmx** [comment]
For me it fixed a torrent glitch in the results count and sped it up a little

**Comment by jewbmx** [comment]
Think imma either add a setting to disable cfscrape or ditch it completely, shits trash lol makes me miss that first couple weeks when i didnt know how to use it so i didnt have any scrapers running it

**Comment by bjgood** [comment]
Hi Jewbmx,
I was wondering why JSergio hasn't accepted your vidtodo, and idtbox submissions yet? I saw that you contacted him via keybase.

Have a good one.

**Comment by jewbmx** [comment]
Probably because he is busy but could also be that vidtodo is half dead domains  and i keep telling him i think idtbox might not be fully coded lol. Might even be the third resolver i edited in that pr which is/was down if i recall

**Comment by jewbmx** [comment]
Im about to push another update later today if i get done with my changes. So i can update my own version of resolveurl if ya want. (Its always gonna be 1v behind)

**Comment by jewbmx** [comment]
Finally spotted a mystream but it failed lol. Gotta see if i can snag the url and check it out.

**Comment by jewbmx** [comment]
Its starting to get old being one of the few people left that actually fix scrapers.

Everyone needs to double check your scrapers that have the fmovies base code. As in the big resolve def using p1 p2 p3 and so on. You get sources but then dont play. Add a little form of debug  and you will notice that most of these scrapers now have a final result of http:https://blahblah 

To make it easier for the dim...

url =  "http:%s" %p2["data"].replace("\/","/")

Needs to be...

url =  "%s" %p2["data"].replace("\/","/")

**Comment by weekendsource** [comment]
I did
```
            url = p2["data"].replace("\/","/")
            if not url.startswith('http'):
                url =  "https:" + url
```
https all the way ;)

**Comment by jewbmx** [comment]
Nice glad someone else caught onto it too lol. I like that bit of code too shouldnt have to worry about it changing and could just toss it on all those scrapers instead of testing each one lol. Think i only seen 1 source pop up in a search thats http so the https is the usual.

**Comment by jewbmx** [comment]
Got a error on that for some reason so i fiddled with it and got this to work too..

`

url =  p2["data"].replace("\/","/")
            if not re.match('(?:http|https):', url):
                url = "https:" + url
            return url

`

**Comment by weekendsource** [comment]
It works here in all scrapers, re is expensive for such a trivial stuff :)) Maybe you messed up indentation?

Try i.e. https://pastebin.com/ZVZ6z1DS

**Comment by jewbmx** [comment]
Just looked at it again and had .startwith instead of .startswith lol

**Comment by weekendsource** [comment]
Obviously a jazz cabbage induced typo ;) Thanks for all the scrapers I stole for my private addon :)))

**Comment by jewbmx** [comment]
Yea i been fat fingerin the shit out of everything the past few days lol. Tested your code change on 123123 too that was still working the old way and got it right this time. About to update em all that way they all match up

**Comment by bjgood** [comment]
Jewbmx,
I've said it before, but I'll say it again...you're one of the good ones. Somebody who spends a lot of time and energy creating or fixing scrapers for everybody. This hobby of ours needs more people like you...not somebody who creates things only for themselves. Enough of that.

I have a question, Jewbmx. In vidics, whenever I do a scan of a series, there's a number of hosts (like bitvid, neodrive, zstream, shared, and others) that will not play. So, as a result, I'd like to block them. Is there a place in the code that represents where the hosts can be manipulated or blocked? 

Here's a link to the version I'm using...
https://github.com/nazegnl/script.module.openscrapers/raw/develop/lib/openscrapers/sources_openscrapers/en/vidics.py

When you have the time could you look it over and see where I can block those hosts? I've tried a number of things but nothing seems to work.

Later...

**Comment by jewbmx** [comment]
Dont know i dont use it so not messing with it lol

**Comment by jewbmx** [comment]
Id try the usual things you see in alot of scrapers like internet and other.

**Comment by bjgood** [comment]
Where to put those code samples is the question. I have no idea where the hosts are dealt with. It's either in the sources function or resolve. That's why I wanted you to look at vidics when you had the time.

Doko, any input on this matter would be appreciated.

Have a good one.

**Comment by Tikipeter** [comment]
Add unwanted hosters to self.hostblockDict in 'getConstants' of the sources.py file.

You must add the full domain of the hoster:

i.e. self.hostblockDict = ['powvideo.net', 'streamplay.to', 'vev.io']

There should then be a filter in 'sourcesFilter' that will get rid of those from the results.

**Comment by bjgood** [comment]
Tikipeter,
Thanks for the reply.

Earlier, I tried putting 'vidzi.online', 'bitvid.sx', 'neodrive.co', 'youtube.com', 'zstream.to', 'shared.sx', 'firedrive.com' (the non-functioning hosts) in self.hostblockDict and it actually blocked them from showing. But, the hosts I was wanting (gorillavid and movpod) would not play when I clicked on them. If I don't include those hosts in hostblockDict gorillavid and movpod do play.

I don't know anything about adding a filter to sourcesFilter.

Again, thanks for the reply.

**Comment by doko-desuka** [comment]
> I've tried a number of things but nothing seems to work.

@bjgood what have you tried, can you show it to me?

**Comment by bjgood** [comment]
Hey doko,
Remembering all the things I've tried is not going to be easy, but one of the first was...

(in the sources function)
if 'bitvid' in data['pageURL']: continue (it's a variation of Jewbmx's code...as you know)

Since if not 'poirot' in data['pageURL']: return restricted vidics to only the Poirot series I assumed that data['pageURL'] would contain host info...but it didn't.

I went to the vidics website, searched for the Poirot series, went to an episode, opened Inspect Element, found the hosts list. The host list should be in langDIV, but it appears not to be for if 'bitvid' in langDIV: continue didn't work either.

I even tried in the resolve function when I noticed...
match = re.search('movie_link1.*?<a.*?href=\"(.*?)\"', r.text, re.DOTALL)
which I found in Inspect Elements. Each individual host segment contained a variation of that code. Each segment contained the host name (example...bitvidsx or neodriveco).

I tried...
for i in match:
    if 'bitvid' in i: continue
...but no luck.

I only want to block/exclude about 7 hosts from showing after a scan of an episode. The only reference to hosts I found was # Find the DIV with English-dubbed hosts, which, I assume, you had put in. This is really not a big deal. I can still go down to gorillavid or movpod. It's more a point of cleaning up the results.

There were other attempts but I can't remember them right now.

Thanks for any help on this, doko.

Later...

**Comment by doko-desuka** [comment]
Ok. I agree with Tikipeter that it's better to do it with the self.hostblockDict method because it'll ignore those sources from all scrapers, not just vidics. It also lets you safely update Openscrapers without losing changes that you'd be making to the vidics scraper.

> Earlier, I tried putting 'vidzi.online', 'bitvid.sx', 'neodrive.co', 'youtube.com', 'zstream.to', 'shared.sx', 'firedrive.com' (the non-functioning hosts) in self.hostblockDict and it actually blocked them from showing. But, the hosts I was wanting, gorillavid and movpod, would show but not play when I clicked on them. If I don't include the non-functioning hosts in hostblockDict gorillavid and movpod do play.

I'd try this again and then look in the Kodi log file for any Resolveurl messages explaining why it couldn't resolve gorillavid or movpod -- the files might've been taken down, for example.

**Comment by bjgood** [comment]
Hi, again, doko,
Just to add, I don't use openscrapers in my setup. I just borrowed vidics from them plus others that I find interesting. Nazegnl had stripped out some of the code and added cfscrape support to your original rework of vidics. It's easy to covert their scrapers over to use in Scrubsv2.

Thanks for your reply, doko.

Later...

**Comment by jewbmx** [comment]
Stupid storm killed my power and net til now lol but you just need to add a simple valid check to that scraper. Dont know why you havent already because that should solve your problem

**Comment by bjgood** [comment]
Must have been a kickass storm to do that. How long were you without power?

Once, due to a heavy, wet snow storm, we were without power for almost a week. Others in my region were without power for almost a month. Makes you really appreciate having power and internet when it comes back on.

Hope everything is alright with you and yours.

Later, Jewbmx.

**Comment by jewbmx** [comment]
Power was a few hours and net was around 10 or so hours lol. Luckily i got a laptop and a external that doesnt use external power :)

**Comment by jewbmx** [comment]
Well thats just gay lol, spent a few minutes adding the tv shows code to a losmoviespro scraper i been sitting on and the site doesnt even have a worthy show section lmao. What a waste of time and effort.

**Comment by jewbmx** [comment]
If anyone gets bored and doesnt mind crashing their kodi they should try to use the search option for a movie but use auto complete to finish the word lol like robin hood selected from robin ho.  On my device it seems to always crash lmao

**Comment by doko-desuka** [comment]
Oof
It must be a lot of code to add that auto complete (keeping a file cache with previous searches).
It's a nice behavior in Google or stuff like that, but in my MXQ 4K (Android) device I'd rather just type in the extra letters for it to be a bit faster hahaha

**Comment by jewbmx** [comment]
I assume its something like a api call with a good amount of strange code lol, i keeps it setup and active on my main device just as a lazy stoner spell check but usually never click it

**Comment by jewbmx** [comment]
If anyone wants to take over my BB or TT addons feel free to, i am thinking about removing em since i dont like the jen template anymore. All i ask is that my names removed.

**Comment by host505** [comment]
Hiya magnetdl as you might know went down, but it only takes to change the domain & base_link to torrentquest.com (sister site) for the scraper to work again.

**Comment by bjgood** [comment]
Hey Jewbmx,
What's up, dude? You've been awfully quiet. No scraper updates? Tempest is not updating either.

Have a good one, bud.

**Comment by Tempest0580** [comment]
I don't know about Jewbmx. Bu I was out of town. I'll be doing some updates this week. I have another project that's been taking alot of my time also.

**Comment by jewbmx** [comment]
I thought my progress/plans was pretty well displayed between the changelog and activity feed lol. Im in tvmaze hell rebuilding the networks section and a few userlists. Been about done but the rainy weather keeps kicking my nets ass

**Comment by jewbmx** [comment]
Just updated, if anyone spots a error let me know, got a little bored near the end of that venture lol. Would of been up last night but i got a headache and needed to get rid of it first.

**Comment by jewbmx** [comment]
Think i might put off the userlist changes to redo most the scrapers. You search something simple like dracula 1992 and all you get is dracula 2000 results lol.

**Comment by bjgood** [comment]
And you call what I like to watch as "weird". Come on. Dracula 1992? Ultra weido, if you ask me. ;).

Later, dude.

**Comment by jewbmx** [comment]
Lol who compares a odd random show to a classic old movie :p

Looks like all the Fluxus IPTV Channel lists are gonna no longer need to be updated every month so yay for that.
