### ISSUE TITLE
Some devices not updating

### ISSUE THREAD

**Issue by nmyshkin** [jewbmx/repo#24]
First, great work!

I have a puzzle. Disclaimer: most devices run Leia 18.9, one runs a patched version of pre-cursor to Krypton(!).

Still, tablet I am writing this on (Android 8.1) is one of only two devices that automatically update when new versions are released. Other Android installs (6.01, 7.0, 11) do not. Settings are same as far as I can tell. Windows installs (7 and 10) also fail to update.

I was shocked the other day to see the patched pseudo-Krypton version, running on a KitKat device, update on its own!

Any thoughts? Maybe an xml or python file to check somewhere? The devices which do not auto update won't update if told to. I must download the new zips and install from there.

Again, just really excellent work. Yours is the only addon we use.

**Comment by jewbmx** [comment]
Gonna need you to reply with less jibber jabber and more to the point 😉 otherwise use the reddit approach to solve whatever problem/problems your having lol.

**Comment by scoob1** [comment]
Hey man first thanks for keeping scrubs going.
Theres an issue that has started again which happened a few months ago but you managed to fix it that time but it has come back sometime over the last few updates.
I have my library set up on kodi from a list of tv shows on trakt,so when scrubs checks daily to update library,it adds new shows/episodes from my trakt list to my kodi library.But since recently i have noticed that new seasons of shows have not been getting picked up by scrubs.
As an example i already had the first 3 seasons of jack ryan added and was waiting for season 4 this month but the new season never got added when it aired.
I have to go into my tv show list on scrubs and then add the new season manually to the library and now it picks up the episodes weekly when they are aired and adds to my library like it should.
Another example is foundation.I have season 1 but season 2 should have been picked up but it hasnt so i have had to add the new season manually.
For some reason,new seasons of tv shows are not being picked up by scrubs when they air,but once added manually then the episodes get picked up and added fine.
Hope you can help as this exact same thing happened a couple moth ago and whatever you did to fix it that time did work before something got changed again to break it :grimacing: I hope you can work your magic again Thanks! :laughing:

**Comment by jewbmx** [comment]
Blah blah stopped reading 1/3rd of the way thru 🙄  stoners might talk long but they dont read long 😴
