### ISSUE TITLE
settings bug

### ISSUE THREAD

**Issue by anon2018** [jewbmx/repo#29]
I found one BUG, in foreign providers there is a blank dot at the bottom, and bottom sections are not scroling good, it makes some problems and kodi close off sometimes

**Comment by jewbmx** [comment]
Sounds like a scraper you had me add in is labeled with the same name. And the foreign providers settings tab has too many lines now.

**Comment by anon2018** [comment]
https://ibb.co/hfLGPdq

**Comment by jewbmx** [comment]
The problem is that each settings.xml section/tab is limited to 80 lines on kodi 18 and thanks to the new providers added it got about 10 too many. So if this effects anyone before my next update, you can simply open the file and delete 10 providers that you use. Or any random 10 or so lines in the section.

**Comment by jewbmx** [comment]
Also notepad++ is for computers bud not phones lol. My only friend is QuickEdit Pro

**Comment by host505** [comment]
@jewbmx not sure if this will have an impact but you could delete all your "sep" type settings above your "lsep"s. They're not needed, because "lsep" places a separator above it's label anyway.

**Comment by jewbmx** [comment]
Yea i been thinking about ditchin em for a while but like the structure more lol my ocd is a pain in the ass. I went ahead and split that provider tab into 2 lol. Next issues gonna be my ocd wanting to reduce the amount of tabs tho.

**Comment by jewbmx** [comment]
Hey host while your online and got me thinking, whats your new trakt settings usefulness? Curious about it for the tvshow new episodes / progress section lol

**Comment by host505** [comment]
Which one, the 'Sync watched status' or the 'resume point source'?
First one just caches your trakt's watched statuses into the add-on's db every time the add-on launches.
Second one lets you choose if resume points will be fetched from trakt (scrobbles) or add-on's local db.
This one only makes sense for incursion based add-ons, that have the Trakt bookmarks code. I think yours is based off placenta?

**Comment by jewbmx** [comment]
It was the watched status one, just checked the addon. Seen it on your activity feed a bit back lol. 
Id have to check my addons code but i think i added the second one a few months ago or started to.

**Comment by host505** [comment]
I don't see yours to have the 'Trakt bookmarks' setting/code.
I have noticed quite a few add-ons that have the 'Trakt bookmarks' setting but lack the code to support it lol.
It should be under player.py/bookmarks class. This is from the Incursion add-on, but I fixed it because it was not working and made some other changes as well.

**Comment by jewbmx** [comment]
Oh yea i remember now lol, i had it about 2/3rds of the way done and forgot my place after taking a break. Then removed what i had done and the settings not that long ago. Ended up just wanting the auto setting in the end.
