### ISSUE TITLE
No content under Movies\In theaters at Scrumbs v2

### ISSUE THREAD

**Issue by chrisnikol** [jewbmx/repo#30]
As the title says at scrumbs v2 if i go at Movies -> In Theaters i cant see any content.
IF i go at movies -> In Theaters (Old style) or TMDB everything is ok.

I already tried to clear the cache but this dident made any difference.

At the setting of scrumb v2 i have the hide movies in cinema disabled.

The version of scrumbs v2 i have installed is 4.4.9 at kodi 18.3 64 bit OS win 10 pro 64 bit 1903.

You can see the behavior of the addon as i described at the video below. In case you needed i can send you and log file.

https://youtu.be/LEuLKyy880Q

Thank you for this amazing addon.

**Comment by jewbmx** [comment]
None of that is needed and your typein the name wrong like a (singular [AfdonName]) lol.

In Theaters isnt in that setting either because thats a oxymoron.

The url used is this which works just fine but depends on your location... https://www.imdb.com/showtimes/location?ref_=inth_ov_sh_sm

It doesnt seem to work for everyone but its nice for folks like me that live in overpopulated areas infested with movie theaters lol.

**Comment by chrisnikol** [comment]
Thanks for your fast response. You helped me to understand why this is happening.

You are absoluty right. When i used VPN and connected at Server who is Located at Los Angeles, i could see the movies catalogue.
