### ISSUE TITLE
new verion/just issues

### ISSUE THREAD

**Issue by anon2018** [jewbmx/repo#31]
More stuff: 
Legends of Music, 
Fitens Zone, 
Kids Corner, 
Movie+TV reviews and trailers,
Tunes
SETTINGS:
Navigation - no on/off buttons for some menu in movies/tv for trakt/tmdb menus
xxx  button suggests that XXX menu will be in MAIN MENU not in more stuff (need to add descryprtion or move)

**Comment by jewbmx** [comment]
Wanna shed a little light and use some detail lol, or shall i just fish all night

**Comment by jewbmx** [comment]
Looks like everything in More Stuff you listed is broken because the creator Muad Dib broke the urls changing his repos around. I was already planning on changing that all up to get off his teet so besides a wait that no biggie lol.

Tunes is working fine here so ya might need to adjust its settings to match your location.(Found in general at the bottom.)

As for your settings part, that might need some detail lol.
But the xxx setting was done that way to make it simple yet not too simple. Gonna clean that section up one of these days so i can touch the setting up too while im at it.

**Comment by jewbmx** [comment]
Think i have everything you listed here fixed now on my end. So it should be all good once i upload.

Only thing that isnt checked off is the Tunes issue awaiting feedback from ya lol
