### ISSUE TITLE
Trakt no more..?

### ISSUE THREAD

**Issue by Nemesis195** [jewbmx/repo#35]
Hi & congrats for your really great addon! There is an issue with trakt last days.. "movies/my movies/collection..(nothing)" 17.6 kodi. I do the trakt authorization again & again but nothing. Be well!

**Comment by jewbmx** [comment]
If your gonna use my addons id highly suggest being on a kodi 18 version, i updated to 18 a decent while back on every device so cant really test on 17 anymore lol.

But as for your problem i assume its something on your end, i dont think i changed any trakt based code since around 3 updates ago or more.  Maybe clear all option in Tools, going over all the settings in Settings, and maybe even double checking the script.trakt addon/module.

**Comment by jewbmx** [comment]
Collection is working for me on 2 devices with both trakt and imdb so not sure lol. Isnt a trakt server issue either from what their site shows  http://status.trakt.tv/

**Comment by Nemesis195** [comment]
Following your advice clear all option in tools, going over all the settings in settings finally it works!! So.. 👍

**Comment by jewbmx** [comment]
Thats good, life without trakt is just no life at all lol.
