### ISSUE TITLE
Scrubs not loading IMDB tv watchlist

### ISSUE THREAD

**Issue by rmeuth01** [jewbmx/repo#36]
Running Kodi 18.3, Scrubs v2, updated to latest version. Starting yesterday, scrubs stopped retrieving season lists from my IMDB watchlist. I cleared caches, now it won't load the show lists at all. I re-checked my accounts, added my personal TMDB and OMDB keys, no luck. 

The IMDB movie list does work, though.

https://paste.kodi.tv/umacejaxuv

**Comment by jewbmx** [comment]
I noticed the problem a couple days ago and been looking for the cause. Havent really changed anything that would cause it and compared old versions to the new to double check.
Since i havent found any real errors i think the problem is just one of the many api keys needed so guess its time for em all to get a update lol.

**Comment by weekendsource** [comment]
If someone opens keybase he shall find the answer ;)

**Comment by jewbmx** [comment]
Just uploaded the update for this error so thank weekendsource for it :)
