### ISSUE TITLE
ustvgo not working in Scrubs

### ISSUE THREAD

**Issue by RickFromTexas** [jewbmx/repo#41]
Just tried playing a few channels but none worked.

**Comment by jewbmx** [comment]
Should be working fine in you applied the fix yourself. Just tested it and still good

**Comment by RickFromTexas** [comment]
Not sure how to apply the fix, unfortunately for me...
________________________________

**Comment by jewbmx** [comment]
If you have access to your folders like a pc or phone then ya just gotta open the indexer folder in my addon then you can replace the contents of ustvgo.py with what i posted the other day on a text site.

Otherwise id suggest you download Tempest or TempTV since he has already pushed a update with the changes in it.

Im atleast a week or two away from my own updates
