### ISSUE TITLE
Streams 

### ISSUE THREAD

**Issue by pat-are** [jewbmx/repo#44]
Hi Andrew! 

Hope you are doing fine and the rest.

Andrew, I have removed all providers that pulls up rabbit stream because they don’t work.

Mostly all new tv series for the year  2024 doesn’t have streamers and does that do has one stream showing when click is says no stream available.
For example in tv serie S.W.A.T season 7 the episodes has one stream it name gdriveplayer.us/movstreamhd.pro.

Thank you for your hard work.

Have lovely day

**Comment by pat-are** [comment]
Most of the tv show’s for the year 2024 new episodes pull up stream sd/watchserieshd.stream/doood.com and you click one it, it says no streams available. Help please

**Comment by pat-are** [comment]
Hi Guy’s, good morning!

Here I’m sending a video showing that I’m not receiving streams for tv series. This video is from the serie Ghosts. There is a lot of series for the year 2024 tv series doesn’t either. It’s has been going on for quite awhile now.

I have authorized my TMDb and Trakt account still doesn’t pull up streams. 

Any help please.

**Comment by pat-are** [comment]
Sorry, with movies I don’t have any problems

**Comment by jewbmx** [comment]
Go find yourself Diggz Free99 addon and stop complaining lol

**Comment by pat-are** [comment]
So Diggz Free99 is better than Scrubs, going to see to find it, thank you.
And don’t worry I won’t be complaining by you guy’s anymore. Have a blessed weekend

**Comment by jewbmx** [comment]
I wouldn't say any addon is better then scrubs lol especially a fork of scrubs, that would be kind of a oxymoron since its still in the early stages of a fork and doesnt even have a new scraper made for it from what i heard. But it can probably run a little faster with the bad scrapers cleaned out of the mix.
To be honest the only addon i find to have anything im envious of is the otaku addon for anime because its got a few nice features ive enjoyed since i started using it even tho id probably never try to put them into my own addon lmao
