### ISSUE TITLE
Scraper Issues

### ISSUE THREAD

**Issue by jewbmx** [jewbmx/repo#6]
This posts for basic chat or issue purposes but also wanna spread the word to any other scraper junkies, your cfscrape changes to scrapers like 123123... will not work! results are not able to be played lol, about everyone in the kodi scene has them in their addons so you might wanna check better when you test em lol.

Heres the issue. (Resolve section with ip_player)

` self.scraper.get('http://123123movies.net/ip.file/swf/plugins/ipplugins.php', post=post, referer=urldata['url'], XHR=True).content `

XHR=True or XHR  is in the client module but not used in cfscrape which seems to be the cause as far as i can tell. (Feel free to share your input or figure out a fix.)

I'll probably toss a quick list of the scrapers using this code in a comment soon.

**Comment by jewbmx** [comment]
Dont know if anyone wants to play with tor scrapers but if ya do i came across a couple decent urls..

https://www.skytorrents.to

https://itorrents.org

**Comment by jewbmx** [comment]
cartoonhd and watchserieshd are broken as of now, might wanna disable them for now. I dont wanna do a update lol.

cartoonhd is .nl right now and has cloudflare enabled, also cfscrape wont solve the issue due to the scrapers xhr use.

watchserieshd is just simply down lol both domains are the same website so times the only fix.

**Comment by Tempest0580** [comment]
cartoonhd is working fine on my end, even without changing the domain. watchserieshd seems to be having server issue so not able to test it much on my end.

**Comment by jewbmx** [comment]
Same here, looks like cartoonhd's CF was temporary and watchserireshd has .co back up running sluggish and the .io is still down

**Comment by jewbmx** [comment]
123123 and 123movieshubz are back to normal instead of CF

**Comment by jewbmx** [comment]
@Tempest0580 can i ask how ya find the urls you come across for your new scrapers? Also looked at the most recent 3 or 4 and think if you wanna do that 1click option some people use they would be good for it lol.

**Comment by Tempest0580** [comment]
Honestly I just search and search the internet. I'll look into doing the 1click option. I have around a dozen more sites like those I'm looking at now. And im going to be adding some tv show sources to a few of the scrapers I created recently.

**Comment by jewbmx** [comment]
I havent had much interest in the 1click options because it is alot of maintenance and upkeep but those sites seem to be perfect for it lol and making lists can be fun till its not lmao

**Comment by jewbmx** [comment]
Got bored and tossed one together on my phone for fun from the ns scraper lol. Missing indents and thumbnails but all yours if you want it.

It was tested in my iptv list on scrubs a minute ago and loads all good and quick.
 http://jewrepo.cf/JewRepo/4git/1clicks.txt

**Comment by doko-desuka** [comment]
> Heres the issue. (Resolve section with ip_player)
> 
> `self.scraper.get('http://123123movies.net/ip.file/swf/plugins/ipplugins.php', post=post, referer=urldata['url'], XHR=True).content`
> 
> XHR=True or XHR is in the client module but not used in cfscrape which seems to be the cause as far as i can tell. (Feel free to share your input or figure out a fix.)

Shalom!
XHR stands for "XmlHttpRequest", it's to do with Javascript and secure web requests, something like that.  
Since we're forging fake web requests and `cfscrape` is an extended `requests.Session` class, in most cases when scraping you can add a "X-Requested-With" header with value "XMLHttpRequest", like in here:
https://github.com/I-A-C/script.module.lambdascrapers/blob/master/lib/lambdascrapers/sources_%20lambdascrapers/en/plocker.py#L220-L225

But the only reason I know it should be that way is because I saw the browser doing requests like those while surfing on the site to be scraped.  
On FireFox (desktop) you can press F12 to open the dev. console -> Network tab -> click on web requests to inspect the headers used, cookies, url parameters, the response etc.

**Comment by jewbmx** [comment]
Im a lil stoned right now but i will be playing around with this later today. Ymovies will be a nice scraper to try on since it uses the xhr setting as well and needs cfscrape atm.

**Comment by doko-desuka** [comment]
lol enjoy the trip

**Comment by Tempest0580** [comment]
Jewbmx did you have any luck figuring this out? I haven't really had a lot of time to sit down and look into it. Lol

**Comment by jewbmx** [comment]
Nope been putting it off too lol, got stuck on a couple new tv shows that got me sucked in

**Comment by Tempest0580** [comment]
I understand. Been there myself lol.

**Comment by doko-desuka** [comment]
>self.scraper.get('http\://123123movies.net/ip.file/swf/plugins/ipplugins.php', post=post, referer=urldata['url'], XHR=True).content

Can be replaced with:

```
self.scraper.headers.update(
  {
    'Referer': urldata['url'],
    'X-Requested-With': 'XMLHttpRequest'
  }
)
self.scraper.post('http://123123movies.net/ip.file/swf/plugins/ipplugins.php', data=post).content
del self.scraper.headers['X-Requested-With'] # Only use it with requests that need it.
```

**Comment by jewbmx** [comment]
Opps didnt mean to close this lol wrong kinda close.

**Comment by jewbmx** [comment]
Apparently the old cfscrape modules we all use in exo forks have suddenly broke most likely from a cloudflare update. Didnt notice personally because i dont use em on my own kodi lol.

Eggman updated his addons with a fix for the issue so i went ahead and pulled em out for anyone that needs em and wants to be lazy lol

http://jewrepo.cf/JewRepo/4git/CFscrape.zip

**Comment by jewbmx** [comment]
Havent tested or looked at any of this besides tossin it in and doing a fast search then exiting. Seems sluggish compared to before but boowhoo lol. Also a tip for the stoned people, if ya got the cfscrape folder plus the normal named py files you can remove the folder version otherwise you will probably have to rename and copy the files to there as well to make sure your addon doesnt get hung up on them.

**Comment by host505** [comment]
Yeah, that's basically what tempest said 2 days ago.
And, for the record, I first saw the fix on the clowns' repo, then eggman updated his too - not sure if that's where it originated though.

**Comment by jewbmx** [comment]
Tempest and i were talking about a totally different CF issue that was just a little thing for like 7 scrapers lol.

Also didnt look around to see where the new files may of came from, i seen eggmans update and noticed the big cf issue that way lol.

**Comment by jewbmx** [comment]
Doko i think the only change was in cfscrape too but tossed em both around because i count them as 1 two part file. I didnt read all the code but did notice its still one version below the real actual sources version on git.

**Comment by jewbmx** [comment]
Looks like Tempest had these CFscrape files first compared to the addons i follow so he might know what is different doko

**Comment by Tempest0580** [comment]
Props to 13clowns of whoever came up with the cfscrape fix. I did a quick test last night and it did fix at least 4 of my major scrapers. I'll do more testing and a update after work.

**Comment by Tempest0580** [comment]
Looks like they rewrote the solve_cf_challenge area the eliminate the need of node.js.

**Comment by jewbmx** [comment]
Yea just compared yours with the fix and was gonna post for doko to see and tossed it on my server lol

http://jewrepo.cf/JewRepo/4git/cfscrapeB4.py

**Comment by doko-desuka** [comment]
I think it was in Incursion or Placenta where it started, in the /modules/ folder there was a cfscrape.py and cfdecoder.py as well as yet another folder called cfscrape, with an __init__.py (making this folder a Python package) and a cfdecoder.py. In the __init__.py there's that class from that file that uses the cfdecoder in that folder.

I think what they did is just delete the duplicates and keep the ones from the package folder. The cloudflare solving formula is still the same (an alternative algorithm is in Team Universal's, [in here](https://github.com/teamuniversal/scrapers/blob/master/_modules4all/script.module.universalscrapers/lib/universalscrapers/modules/cfscrape.py)).

**Comment by bugatsinho** [comment]
i thought it would be read in reddit but noone saw it!about scrapers on exodus forks or also in any other scraper module you have to consider using the modules are made for many things because they created for a reason...i saw many weird code writting in many new scrapers and i suppose its because you cant import the modules working on notepad++ or sublime!here some reasons why you have to use the modules!
https://www.reddit.com/r/Addons4Kodi/comments/afdqgb/to_every_dev_creatingfixing_scrapers_for_exodus/

**Comment by doko-desuka** [comment]
> "TO Every DEV creating-fixing scrapers for exodus fork"
> [removed]

There's nothing there bruh

**Comment by bugatsinho** [comment]
![image](https://user-images.githubusercontent.com/18536253/51547070-8da3d300-1e33-11e9-826e-2e4af380968b.png)

**Comment by bugatsinho** [comment]
> > "TO Every DEV creating-fixing scrapers for exodus fork"
> > [removed]
> 
> There's nothing there bruh

![image](https://user-images.githubusercontent.com/18536253/51547264-eb381f80-1e33-11e9-901b-a9564ed2ce93.png)

**Comment by jewbmx** [comment]
Either my git app is fucked up or yall are deletein posts lol, luckily email catches all of it. Doko that person is posting some reddit shit that basically says we all need to use the host check feature for every scraper to help counter the no craptcha option in settings lol. Had to copy the url and remove the trash before it would load

**Comment by host505** [comment]
@bugatsinho your Reddit post was probably deleted, doesn't load for me too. Try to see it while logged-out of Reddit.
Anyway, we read it now on your pic, and I totally agree, there's lots of stuff in the modules that simplify the process. Maybe the best example is the recent event with cf, you fix the module, a bunch of scrapers got fixed. If every scraper had it's own cf function, all would need fixing, one by one.
@jewbmx 'that person' has written tons of scrapers since the covenant days, some for uni scrapers as well that you probably use on your Jen add-on lol better listen to the guy.

**Comment by bugatsinho** [comment]
Thank you @host505 !
Universal Scrapers cfscrape.py updated since Last September...when i did some work on smus by adding modules that make coding easier...also this recommendation on reddit  wasnt only for that issue but im seeing scrapers that have in their code copy-paste modules that easily you could import them to your scraper.

**Comment by jewbmx** [comment]
Double check your in theaters url for your addons, one of the imdb options i use is now only showing 1 movie lol. Theres 4 or more urls used for it so you might not have this issue and if you do theres 3 or more other ones to use lmao

**Comment by jewbmx** [comment]
As for the scraper mod convo, i didnt mean for my post to sound offensive thats just how i talk. Also its not listen buddy its read :)  i actually already use what he is talking about but i spend most my dev time trying to fix the quality code in scrapers.

Can say i thought that code only made it so the pair popup didnt show up and the source would be skipped in the list lol. Didnt know its supposed to ditch those gay openload sources completely.

**Comment by drchud** [comment]
Hell i might as well join in too lol.
@host505 Don't be an ass clown! Do you really think 13 clowns first had a fix lol?
For one they are copy and pasters too, not real devs. They just play with xmls, maybe they got bored of their jen addons lol.
So to even make that statement shows how much u really know...jack!
Im 99.9 percent sure someone with some kodi knowledge just tipped them off. Does it even really matter, they have stolen every scrapper and no fixes when they break. I find it pretty fucking funny they created a scraper module for "the community". When in reality they don't provide any better service to the community that say another copy and paster like eggman.
Sorry just needed to speak some truth

**Comment by host505** [comment]
Well tbh no I don't think they actually fixed it, what I said is 

>  I first saw the fix on the clowns' repo, then eggman updated his too - not sure if that's where it originated though.

I just wanted to point out that eggman didn't for sure fix it, because they updated their repo minutes after 13c did.

**Comment by drchud** [comment]
lol don't forget the beginning of that sentence 

> And, for the record, I first saw the fix on the clowns' repo, 
You made it sound that way dude. Listen this wouldn't be an issue if everone was running ver 1.9.5 from anorov.  Luckly i was already using the current one cause it was released a lot time ago lol.
Thats not to say it perfect cause im still getting errors from time to time.

**Comment by drchud** [comment]
lol oh no the black copy and paster that is also a fake dev

**Comment by drchud** [comment]
Your dev time lol, go play with ur xmls too

**Comment by host505** [comment]
@drchud do you not realise the difference between 'first saw' and actually believing that _they_ fixed it?
jewbmx sorry to respond pall, might as well delete my own comments too.

**Comment by jewbmx** [comment]
Ill delete that last one for ya lol already blocked him so he should need a new troll account before he can work that cum catcher again

**Comment by doko-desuka** [comment]
@bugatsinho thanks for the screenshots, it looked as if deleted to me

**Comment by doko-desuka** [comment]
Yo, if anyone wanna test this out (because I haven't): calling MX Player to play a video from Kodi.  

Sometimes the built-in Kodi player stinks, it doesn't buffer well (it stops buffering when you pause the video), or when you go back ten seconds it causes a new rebuffer (when it should've played from memory cache), so maybe for some sources MX Player will do a better job at streaming.

Using these references...
- https://forum.kodi.tv/showthread.php?tid=232485&pid=2314046#pid2314046
- https://android.stackexchange.com/questions/141325/tasker-play-video-using-mx-player-while-another-is-currently-playing#comment189487_141390
- https://stackoverflow.com/a/28638589

...we'd be able to send the stream to MX Player to play, it would be something like this:

```
import os
from itertools import chain

# Get a resolved URL from ResolveURL.
resolvedURL = HostedMediaFile(url=...).resolve()

# Make a string out of the headers that were meant for Kodi to use.
headers = '","'.join(chain.from_iterable(pair.split('=') for pair in resolvedURL.split('|', 1)[1].split('&')))

# Send the command using the Android activity manager.
command = r'/system/bin/am start -n com.mxtech.videoplayer.ad/.ActivityScreen -d "{url}" --es "title" "{title}" --es "filename" "{title}" --esa "headers" "{headers}" --user 0 --activity-clear-task'.format(url=resolvedURL, title=..., headers=headers)
os.system(command)
```

Subtitles would have to be searched directly in MX Player using Menu -> Online Subtitles -> Search. Can't send the filepath through this command line (it doesn't use string, it uses an android.net.Uri object that Python doesn't know about).

PS: We use this way instead of the [StartAndroidActivity built-in](https://kodi.wiki/view/List_of_built-in_functions#Android_built-in.27s) because we need the web headers to access some sources, and because, on different Android installs, the os.system function might not work, so these are alternative ways to call some intent -> https://github.com/zach-morris/plugin.program.iagl/blob/7d04c7cfa8ccb36770a0013d19cf0a25ac8ef65e/resources/lib/main.py#L3878-L3942

**Comment by jewbmx** [comment]
That could make for a nice right click option like autoplay is and trakt manager. Theres 3 or 4 different popular players people use for local already

**Comment by jewbmx** [comment]
Did anyone ever try to add that UpNext addon to a exo fork? I dont really use that kinda option ever but im high enough today to make that feature sound good while i binge watch my shows lol

**Comment by doko-desuka** [comment]
@jewbmx I never tried UpNext. My Android TV box is so cheap, I don't like using services or resident stuff, it just eats up CPU.

**Comment by jewbmx** [comment]
No worries it makes sense to respond here lol.

I havent used it or seen it so probably wont bother with it either. The feature usually annoys me on any other app after a while lol
