### ISSUE TITLE
RD sources not shown/listed in Scrubs v2.

### ISSUE THREAD

**Issue by comonucrows** [jewbmx/repo#8]
Hi mate, just installed Scrubs v2 in my build (19.4). I like the addon, first time using it. However, RD sources are not shown or listed.  I have authorized ResolveUrl twice, checked if Real Debrid account is still active and currently have over a month left. The free links are good and there are plenty of them...But I prefer RD. Is it my end, or is there an issue?

**Comment by jewbmx** [comment]
That is just how i did my addon now. I removed all code/support for paid based shit lol. Thought i posted that somewhere in the addon but might not of since your one of many people with the same issue.
Apologies tho but for paid use everyones gonna have to look elsewhere. Theres definitely plenty of good choices out there for it.
