### ISSUE TITLE
Flatten Seasons, and showing number of episodes left on icons/widgets don't work 

### ISSUE THREAD

**Issue by cgcgcgcgcg** [jewbmx/repo#9]
Skin I use supports showing number of episodes left on other addons.

**Comment by jewbmx** [comment]
Dont know what ya mean about the number bit but the flatten seasons code is still commented out at the moment and was possibly getting removed due to it not being very useful lol.

**Comment by cgcgcgcgcg** [comment]
If you use Trakt TV Collection it's very useful to know how many episodes are out, or left before season ends.
Gives you a reason to live, also sends you to wikipedia or another site to discover if there's going to be another season, or show was cancelled, lol.

**Comment by jewbmx** [comment]
Guessing your talking about some widget or some shit lol because flatten season just folds every season into one big list like a anime show sometimes appears lol.  I personally just use the trakt progress "Episode Widget" section in my addon then when i goto click on a show i usually right click to get to the view seasons menu option and watch my shows from that space.
I might code the flatten option back in for ya to be able to use it but whatever else your sayin will probably not be looked into lol

**Comment by cgcgcgcgcg** [comment]
> Guessing your talking about some widget or some shit lol because flatten season just folds every season into one big list like a anime show sometimes appears lol. I personally just use the trakt progress "Episode Widget" section in my addon then when i goto click on a show i usually right click to get to the view seasons menu option and watch my shows from that space. I might code the flatten option back in for ya to be able to use it but whatever else your sayin will probably not be looked into lol

Actually I don't use widgets but it helps to save clicks there too, if you combine Flatten Seasons with Hide watched, when you open eg your Trakt Library the first episode you see is the first unwatched. This, combined with Hide Unaired, shows first unseen episode then all unseen aired.
I used to tweak Kodi settings for that method to be available in Kodi library when I used it.

https://user-images.githubusercontent.com/38960370/166232726-4966df51-0226-4e15-a234-3363d401f903.mp4
